{
 "title": "AAP - Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(awx_instance_info,namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "query_result(awx_instance_info{namespace=~\"$namespace\"})"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(awx_instance_info{namespace=~\"$namespace\",job=~\"$service\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "License and Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 1, "y": 1 },
   "options": {
    "content": "<!-- <img src=\"https://www.ansible.com/hubfs/Logo-Red_Hat-Ansible_Automation_Platform-A-Standard.svg\"> -->\n<img src=\"https://www.redhat.com/cms/managed-files/ansible-logo_0_0.png\" width=\"200px\" height=\"200px\">\n"
   }
  },
  {
   "title": "Controller Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_system_info{tower_version=~\".*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insights ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "External Logger",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "Hosts Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_license_instance_total" }
   ]
  },
  {
   "title": "Hosts Available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_license_instance_free", "legendFormat": "Available" }
   ]
  },
  {
   "title": "Hosts Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ( awx_license_instance_free / awx_license_instance_total * 100 )",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "License Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "License Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(awx_instance_info{})" }
   ]
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Access",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(awx_users_total)", "legendFormat": "Users" },
    { "expr": "sum(awx_teams_total)", "legendFormat": "Teams" },
    { "expr": "sum(awx_organizations_total)", "legendFormat": "Organizations" },
    { "expr": "sum(awx_sessions_total)", "legendFormat": "Online Users" }
   ]
  },
  {
   "title": "Resources",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(awx_inventories_total)", "legendFormat": "Inventory" },
    { "expr": "sum(awx_projects_total)", "legendFormat": "Projects" },
    { "expr": "sum(awx_job_templates_total)", "legendFormat": "Job Template" },
    {
     "expr": "sum(awx_workflow_job_templates_total)",
     "legendFormat": "Workflow"
    },
    { "expr": "sum(awx_hosts_total)", "legendFormat": "Active Hosts" },
    { "expr": "sum(awx_schedules_total)", "legendFormat": "Schedules" }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(1, awx_instance_cpu)", "legendFormat": "CPU" },
    { "expr": "topk(1,awx_instance_memory)", "legendFormat": "Memory" },
    { "expr": "topk(1, awx_instance_capacity)", "legendFormat": "Forks" }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(awx_instance_consumed_capacity[15m])) ",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(awx_instance_memory[15m])) ",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Job Launched Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(awx_status_total{status=\"error\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(awx_status_total{status=\"error\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(awx_status_total{status=\"canceled\"})",
     "legendFormat": "Canceled"
    },
    {
     "expr": "sum(awx_status_total{status=\"failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(awx_status_total{status=\"successful\"})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(awx_status_total{status=\"waiting\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(awx_status_total{status=\"pending\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Job Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(awx_status_total{status=\"successful\"})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(sum(awx_status_total{status=\"failed\"}) + sum(awx_status_total{status=\"error\"}))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Time Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(task_manager_get_tasks_seconds[5m]))",
     "legendFormat": "Loading Tasks"
    },
    {
     "expr": "avg(rate(task_manager_start_task_seconds[5m]))",
     "legendFormat": "Starting Tasks"
    },
    {
     "expr": "avg(rate(task_manager_process_running_tasks_seconds[5m]))",
     "legendFormat": "Processing Running Tasks"
    },
    {
     "expr": "avg(rate(task_manager_process_pending_tasks_seconds[5m]))",
     "legendFormat": "Processing Pending Tasks"
    }
   ]
  },
  {
   "title": "Transactions Time  - Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(task_manager_commit_seconds[1h]))",
     "legendFormat": "DB Transactions"
    },
    {
     "expr": "avg(rate(dependency_manager_get_tasks_seconds[1h]))",
     "legendFormat": "Loading Pending Tasks from DB"
    },
    {
     "expr": "avg(rate(workflow_manager_get_tasks_seconds[1h]))",
     "legendFormat": "Loading Workflow Tasks from DB"
    },
    {
     "expr": "avg(rate(callback_receiver_events_insert_db_seconds[1h]))",
     "legendFormat": "Saving Events to DB"
    }
   ]
  }
 ]
}