global:
  scrape_interval: 15s  # Adjust based on your needs

scrape_configs:
  - job_name: "ansible_aap"
    metrics_path: "/api/controller/v2/metrics"
    static_configs:
      - targets: [192.168.57.122]
    scheme: https  # Use 'http' if AAP is not using HTTPS
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: "admin"
      password: "aapadmin"
