version: "3.9"
services:
  postgresql-app1:
    image: postgres:latest
    container_name: postgresql-app1
    ports:
      - "5433:5432" # Map container's PostgreSQL port to the host
    environment:
      # POSTGRESQL_USER: "admin"
      # POSTGRESQL_PASSWORD: "securepassword"
      # POSTGRESQL_DATABASE: "appdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "securepassword"
      POSTGRES_DATABASE: "appdb"
    volumes:
      - postgresapp1:/var/lib/pgsql/data:Z
# Important Note: Exposing the password in the environment section is not secure for production deployments.
# Consider using environment variables passed at runtime or secrets management tools.

volumes:
  postgresapp1:
    driver: local
