version: "3.9"


services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana:Z
    environment:
      ## Important Note ##
      ## Exposing the password in the environment section
      ## is not secure for production deployments.
      ## Consider using environment variables passed
      ## at runtime or secrets management tools.
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - monitoring-net
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: "1000:1000"   # Runs Prometheus as the correct user
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring-net

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  monitoring-net:
