version: "3.9"

services:
  gitlab:
    container_name: gitlab-ce
    image: gitlab/gitlab-ce:16.11.1-ce.0
    hostname: gitlab.lab.iamgini.com
    # restart: always
    ports:
      - "8443:443"
      - "8080:80"
      - "2222:22"
    environment:
      - GITLAB_OMNIBUS_CONFIG=external_url 'http://gitlab.lab.iamgini.com:8080';
    secrets:
      - source: gitlab_root_password
        target: GITLAB_ROOT_PASSWORD
        type: env
    volumes:
      - gitlab_config:/etc/gitlab:Z
      - gitlab_logs:/var/log/gitlab:Z
      - gitlab_data:/var/opt/gitlab:Z
    restart: always

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
