version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    hostname: pi-hole
    image: pihole/pihole:latest
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
      - "1067:67/udp"
      - "1080:80/tcp"
      - "1443:443/tcp"
    environment:
      - TZ=Asia/Singapore
      - SERVERIP=192.168.1.20
      - WEBPASSWORD=my_pihole_password
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
      - DNSSEC=true
      - CONDITIONAL_FORWARDING=true
      - CONDITIONAL_FORWARDING_IP=192.168.1.1
      - CONDITIONAL_FORWARDING_DOMAIN=lan
      - TEMPERATUREUNIT=c
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      # - './etc-pihole/:/etc/pihole/'
      # - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - pihole_pihole:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

volumes:
  pihole_pihole:
  pihole_dnsmasq:
