ARG BUILD_FROM=alpine:latest

FROM $BUILD_FROM

RUN apk --update --no-cache add bash nfs-utils rpcbind && \
    rm -v /etc/idmapd.conf /etc/exports

RUN mkdir -p /var/lib/nfs/rpc_pipefs /var/lib/nfs/v4recovery && \
    echo "rpc_pipefs /var/lib/nfs/rpc_pipefs rpc_pipefs defaults 0 0" >> /etc/fstab && \
    echo "nfsd /proc/fs/nfsd nfsd defaults 0 0" >> /etc/fstab

# Configure rpcbind for NFSv4
RUN mkdir -p /run/rpcbind

# Expose necessary ports for NFS and rpcbind
EXPOSE 2049 111/udp 111/tcp

# Entrypoint script to start NFS services
COPY ./entrypoint.sh /usr/local/bin
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
